name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cicd-learning .

      - name: Run container and test
        run: |
          docker run --name test-container cicd-learning
          echo "Container test passed!"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag image
        run: docker tag cicd-learning ${{ secrets.DOCKER_USERNAME }}/cicd-learning:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-learning:latest